### ISSUE TITLE
Add Guns

### ISSUE THREAD

**Issue by RelativeForce** [RelativeForce/CS3010-FinalYearProject#85]
## Details:
Approved Date: 25/12/19
Points Spent: 4+4+1+2+1= 12

## Background
Currently, the player and enemies just fire bullets out of thin air. This does not conform to the desired quality of the game.

## Overview
- [x] Add support for guns #83 
- [x] Add support for limited bullets in guns #90 
- [x] Add gun pickups #84 
- [x] Add shot gun #102 
- [x] Add assault rifle #105 

## Acceptance Criteria
This epic is complete when all the sub-issues within it are completed.

## Closing Notes

The guns have been added in a generic way such that they can be used for both enemies and the player. This provides a good basis for future improvement.

## Technical Challenges
None
